# Generated by Django 2.2.16 on 2022-11-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
        ('posts', '0008_post_image'),
    ]

    operations = [
    ]
